name: Update Comic

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Comic
    runs-on: ubuntu-latest
    env:
      PUBLIC_VAPID_KEY: ${{ secrets.PUBLIC_VAPID_KEY }}
      SECRET_VAPID_KEY: ${{ secrets.SECRET_VAPID_KEY }}
      NETTRUYEN_URL: ${{ secrets.NETTRUYEN_URL }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Run update script
        run: npm run update
